name: wykmonke
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^0.14.0+3
  http: ^0.13.0
  syncfusion_flutter_sliders: ^19.3.44
  web3dart: ^2.3.1
  velocity_x: ^3.4.0
  # velocity_x: ^0.12.2
  # http: ^0.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - .env
    - assets/images/abi.json