name: wykmonke
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^0.14.0+3
  http: ^0.13.0
  syncfusion_flutter_sliders: ^19.3.44
  web3dart: ^2.3.1
  velocity_x: ^3.4.0
  dio: ^4.0.4
  cached_network_image: ^3.0.0
  flutter_svg: ^0.22.0
  syncfusion_flutter_charts: ^19.1.67
  intl: ^0.17.0
  # cupertino_icons: ^1.0.2
  # firebase_core: ^1.13.1 
  # firebase_auth: ^3.3.8
  # provider: ^6.0.2
  # cloud_firestore: ^3.1.9
  # velocity_x: ^0.12.2
  # http: ^0.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - .env
    - assets/abi.json
    - assets/icons/
    - assets/images/